[package]
name = "spider-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.147"
serde_json = "1.0.89"
async-trait = "0.1.58"
futures = "0.3.25"
log = "0.4.17"